name: 'CD pong'
description: 'Triggered by a CI ping event to update dependencies and make a PR'
inputs:
  repository:
    description: 'The repository name'
    required: true
  dependency:
    description: 'The used dependency'
    required: true
  tag:
    description: 'The pushed tag of the used dependency'
    required: true
  hash:
    description: 'The zig hash of the pushed tag of the used dependency'
    required: true
  token:
    description: 'The github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: tiawl/spaceporn-action-env@1.0.1

    - uses: actions/checkout@v4
      with:
        repository: "${{ inputs.repository }}"
        token: "${{ inputs.token }}"

    - name: Setup git user information
      env:
        BRANCH: "${{ env.bot_branch }}"
        EMAIL: "${{ env.gh_bot_email }}"
        HASH: "${{ inputs.hash }}"
        NAME: "${{ env.gh_bot_name }}"
      shell: ${{ env.shell }}
      run: |
        git config user.name "${NAME}"
        git config user.email "${EMAIL}"
        git checkout -b "${BRANCH}"
        printf 'hash_len=%s\n' "${#HASH}" >> "${GITHUB_ENV}"

    - name: Update github actions files
      if: env.hash_len == '0'
      env:
        REPOSITORY: "${{ github.repository_owner }}/${{ inputs.dependency }}"
        TAG: "${{ inputs.tag }}"
      shell: ${{ env.shell }}
      run: |
        find . -type f -name '*.yml' -exec sed -i "s#uses:\s*${REPOSITORY}@v.\+#uses: ${REPOSITORY}@${TAG}#g" {} +

    - name: Setup Zig
      if: env.hash_len != '0'
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: ${{ env.zig_version }}

    - name: Update the build.zig.zon
      if: env.hash_len != '0'
      env:
        URL: "${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.dependency }}/archive"
        TAG: "${{ inputs.tag }}"
        HASH: "${{ inputs.hash }}"
      shell: ${{ env.shell }}
      run: |
        zon_url="$(grep -o "${URL}/.*\.tar\.gz" build.zig.zon)"
        zon_hash="$(zig fetch "${zon_url}")"
        sed -i "s@${zon_url}@${URL}/refs/tags/${TAG}.tar.gz@;
                s@${zon_hash}@${HASH}@" build.zig.zon

    - name: Diff
      id: diff
      shell: ${{ env.shell }}
      run: |
        diffs="$(git diff HEAD --name-only | wc -l)"
        printf 'len=%s\n' "${diffs}" >> "${GITHUB_OUTPUT}"

    - name: Create Pull Request
      if: steps.diff.outputs.len != '0'
      env:
        BRANCH: "${{ env.bot_branch }}"
        DEFAULT: "${{ env.default_branch }}"
        GH_TOKEN: "${{ inputs.token }}"
        TITLE: "${{ env.gh_bot_pr_title }}"
      shell: ${{ env.shell }}
      run: |
        git add -A
        git commit -m "CD: ${TITLE}"
        git push --force --set-upstream origin "${BRANCH}"
        gh pr create --base "${DEFAULT}" --fill --assignee "${GITHUB_REPOSITORY_OWNER}" || :
