name: 'CD pong'
description: 'Triggered by a CI ping event to update dependencies and make a PR'
inputs:
  dependency:
    description: 'The used dependency'
    required: true
  tag:
    description: 'The pushed tag of the used dependency'
    required: true
  hash:
    description: 'The zig hash of the pushed tag of the used dependency'
    required: true
  token:
    description: 'The github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: tiawl/spaceporn-dep-action-env@v1

    - name: Setup git user information
      shell: ${{ env.shell }}
      run: |
        git config user.name "${{ env.gh_bot_name }}"
        git config user.email "${{ env.gh_bot_email }}"
        git checkout -b "${{ env.bot_branch }}"

    - if: ${{ inputs.hash == '' }}
      uses: ./actions/workflow
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.dependency }}"
        tag: "${{ inputs.tag }}"

    - if: ${{ inputs.hash != '' }}
      uses: ./actions/zig
      with:
        url: "${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.dependency }}/archive"
        tag: "${{ inputs.tag }}"
        hash: "${{ inputs.hash }}"

    - name: Diff
      id: diff
      shell: ${{ env.shell }}
      run: |
        printf 'len=%s\n' "$(git diff HEAD --name-only | wc -l)" >> "${GITHUB_OUTPUT}"

    - name: Create Pull Request
      if: ${{ steps.diff.outputs.len != '0' }}
      shell: ${{ env.shell }}
      run: |
        git add -A
        git commit -m "CD: ${{ env.gh_bot_pr_title }}"
        git push --force --set-upstream origin "${{ env.bot_branch }}"
        gh pr create --base "${{ env.default_branch }}" --fill --reviewer "${GITHUB_REPOSITORY_OWNER}"
      env:
        GH_TOKEN: ${{ inputs.token }}
