name: 'ci'
description: 'Run CI test for CD ping'
inputs:
  dependency:
    description: 'The used dependency'
    required: true
  is_composite:
    description: 'Is this a composite action dependency ?'
    required: false
    default: 'false'
  user:
    description: 'The User of this repository'
    required: true
  token:
    description: 'The github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: tiawl/spaceporn-action-env@v1.0.0
    - uses: goto-bus-stop/setup-zig@v2.2.0
      if: inputs.is_composite != 'true'
      with:
        version: ${{ env.zig_version }}

    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.user }}"

    - name: Search current tag selected by user
      id: used
      env:
        DEPENDENCY: "${{ github.repository_owner }}/${{ inputs.dependency }}"
      shell: bash
      run: |
        tag="$(grep -h -o -R "${DEPENDENCY}@v\S\+" | sed "s#^${DEPENDENCY}@##" | sort -u || :)"
        printf 'tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.dependency }}"
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare CD
      id: prepare
      env:
        IS_COMPOSITE: "${{ inputs.is_composite }}"
        URL: "${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.dependency }}/archive/refs/tags"
        USED: "${{ steps.used.outputs.tag }}"
      shell: bash
      run: |
        tags="$(git tag --points-at "$(git describe --tags --abbrev=0 2> /dev/null)" 2> /dev/null | wc -l || :)"
        if [[ "${tags}" == '1' ]]; then tag="$(git describe --tags --abbrev=0)"; fi
        git show-ref --tags "${tag:-"${USED}"}"
        git checkout "${tag:-"${USED}"}"
        hash="$(if [[ "${IS_COMPOSITE}" != 'true' ]]; then zig fetch "${URL}/${tag:-"${USED}"}.tar.gz"; fi)"
        printf 'hash=%s\n' "${hash}" >> "${GITHUB_OUTPUT}"
        printf 'tag=%s\n' "${tag:-"${USED}"}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.user }}"
        dependency: "${{ inputs.dependency }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        hash: "${{ steps.prepare.outputs.hash }}"
        token: "${{ inputs.token }}"
