name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test-toolbox:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'toolbox'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-vulkan:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'vulkan.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-wayland:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'wayland.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-X11:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'X11.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-glfw:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - cimgui.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'glfw.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-cimgui:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'cimgui.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-spirv:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spirv.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-glslang:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'glslang.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-shaderc:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'shaderc.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-env-action:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-env'
        is_composite: 'true'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-bot-action:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-bot'
        is_composite: 'true'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-ci-action:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-ci'
        is_composite: 'true'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-ping-action:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn-dep-action-env
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-pong
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-cd-ping'
        is_composite: 'true'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-pong-action:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn
          - spaceporn-dep-action-env
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-cd-pong'
        is_composite: 'true'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
