name: cd pong

on:
  repository_dispatch:
    types:
      - ping-from-spaceporn-action-env
      - ping-from-spaceporn-action-cd-ping

jobs:
  pong:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        to: "${{ github.repository }}"
        from: "${{ github.event.client_payload.from }}"
        tag: "${{ github.event.client_payload.tag }}"
        hash: "${{ github.event.client_payload.hash }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
